_BASE_: STEPGRU_BASE.yaml
MODEL:
  PRETRAINED_CHECKPOINT_URL: https://github.com/beasteers/procedural_step_recog/releases/latest/download/M5.pt
  OUTPUT_DIM: 5  

SKILLS:
  - NAME: M5 - X-Stat
    STEPS:
    - Open inner packaging and remove applicator.
    - Insert applicator into wound track as close to bleeding source as possible.
    - Insert plunger into applicator.
    - Push plunger firmly to deploy sponges into wound.
    - Apply manual pressure if necessary.    
