_BASE_: STEPGRU_BASE.yaml
MODEL:
  PRETRAINED_CHECKPOINT_URL: https://github.com/beasteers/procedural_step_recog/release/latest/download/R18.pt
  OUTPUT_DIM: 5  

SKILLS:
  - NAME: R18 - Apply chest seal
    STEPS:
    - With gloved hand, cover and seal wound site. 
    - Open vented chest seal package.
    - Wipe blood and body fluids from wound site.
    - Peel away chest seal backer.
    - Place chest seal with circle of vents over wound site and seal to chest.

