CHECKPOINT: wandb/run-20240417_160138-ioy4g76e/files/best_model.pth
DATASET:
  BATCH_SIZE: 1
  DIR: /vast/irr2020/BBN
  NMACHINESTATES: 3
  NSTEPS: 19
  NWORKERS: 0
  VAL_FOLD: 1
MODEL:
  GRU_DROPOUT: 0.5
  GRU_INPUT_SIZE: 1024
  GRU_NUM_LAYERS: 2
  VID_BACKBONE: omnivore_swinB_epic
  VID_EMBED_SIZE: 1024
  VID_MEAN: [0.485, 0.456, 0.406]
  VID_STD: [0.229, 0.224, 0.225]
  VID_NFRAMES: 32

  USE_STATE_HEAD: false
  SKILL_STEPS:
    M2: [11,12,2,15,6,12,14,7,18]
    M3: [1,8,0,17,14,18]
    M5: [8,4,5,13,1,18]
    R18: [3,8,16,9,10,18]
TRAIN:
  EPOCHS: 50
  LR: 0.001
